version: '2'

services:
  registry:
    restart: always
    image: registry:2
    hostname: docker.mudryy.engineer
    expose:
      - '80'
    networks:
      - proxy
      - default
    environment:
      VIRTUAL_HOST: docker.mudryy.engineer
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 80
      REGISTRY_HTTP_TLS_CERTIFICATE: /etc/letsencrypt/certificate.crt
      REGISTRY_HTTP_TLS_KEY: /etc/letsencrypt/private_key.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - data:/var/lib/registry
      - $HOME/.certs:/etc/letsencrypt:ro
      - $HOME/.secrets/htpasswd:/auth/htpasswd:ro

volumes:
  data:

networks:
  proxy:
    external:
      name: nginxproxy